/* R128 — NOTATKI O FIRMIE: LIVE MASTER CANDIDATE
   Baza: zamrożony R127 OFERTA — LANGUAGE LIVE + CLEAN MASTER.
   Jedyna zmiana: aktywacja kafla nr 5 „NOTATKI O FIRMIE” w Karcie nr 3 RYNKI EU.
   R120 DANE FIRMY, R121 CENY, R122 HISTORIA i R127 OFERTA pozostają nietknięte.
*/
importScripts('./sw-r127-language-base.js?v=R128-company-notes-live');

if(Array.isArray(ASSETS)){
  [
    './grafiki/rynki-eu/szczegoly-firmy/file_0000000086cc8211895d9ec103b101c6.png',
    './grafiki/rynki-eu/szczegoly-firmy/file_00000000bd78820abbb3d95fa03deebb.png'
  ].forEach(function(a){if(!ASSETS.includes(a))ASSETS.push(a);});
}

const r128BasePatchIndexHtml=r48PatchIndexHtml;
r48PatchIndexHtml=function(text){
  let out=r128BasePatchIndexHtml(text);

  /* Zachowanie hotfixu nowej linii z R127. */
  out=out.replace("\\n  function r115RenderCompanyMaster(){","\n  function r115RenderCompanyMaster(){");

  out=out.replaceAll('1.3.0-master-r127-offer-language-clean-master','1.3.0-master-r128-company-notes-live');
  out=out.replaceAll('R127 OFERTA — LANGUAGE LIVE + CLEAN MASTER','R128 NOTATKI O FIRMIE — LIVE MASTER CANDIDATE');
  out=out.replace("const BUILD_TIME = '10:30';","const BUILD_TIME = '16:08';");
  out=out.replace(/sw\.js\?v=R127-offer-language-clean-master-1030/g,'sw.js?v=R128-company-notes-live-1608');
  out=out.replace(/r84-backup-prune\.js\?v=R127-1030/g,'r84-backup-prune.js?v=R128-1608');

  if(!out.includes('r128-company-notes-master-inside-iife')){
    const r128Inside=`
  /* r128-company-notes-master-inside-iife */
  const R128_NOTES_IMG='./grafiki/rynki-eu/szczegoly-firmy/file_0000000086cc8211895d9ec103b101c6.png';
  const R128_NOTES_DETAIL_IMG='./grafiki/rynki-eu/szczegoly-firmy/file_00000000bd78820abbb3d95fa03deebb.png';
  const R128_NOTES_KEY='crm13_r128_company_notes_v1';
  const R128_NOTE_SECTIONS=['facts','offer','conclusions','talk'];
  const R128_NOTE_LABELS={facts:'KLUCZOWE FAKTY',offer:'PARAMETRY OFERTY',conclusions:'WNIOSKI HANDLOWE',talk:'FAKTY DO ROZMOWY'};

  function r128Read(){try{const v=JSON.parse(localStorage.getItem(R128_NOTES_KEY)||'{}');return v&&typeof v==='object'?v:{}}catch(e){return {}}}
  function r128Id(c){return String((c&&c.id)||state.selectedCompany||'').trim()||String((c&&c.name)||'firma').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-')}
  function r128Saved(c){const all=r128Read();return all[r128Id(c)]||{}}
  function r128Write(c,patch){const all=r128Read(),id=r128Id(c),old=all[id]||{};all[id]=Object.assign({},old,patch||{},{updatedAt:new Date().toISOString()});localStorage.setItem(R128_NOTES_KEY,JSON.stringify(all));return all[id]}
  function r128Text(s,text,x,y,w,h,size,color,weight,align){if(text===undefined||text===null||String(text).trim()==='')return;const e=document.createElement('div');e.textContent=String(text);e.style.position='absolute';e.style.left=(x/8.52)+'%';e.style.top=(y/18.46)+'%';e.style.width=(w/8.52)+'%';e.style.height=(h/18.46)+'%';e.style.display='flex';e.style.alignItems='center';e.style.justifyContent=align==='center'?'center':'flex-start';e.style.color=color||'#fff';e.style.fontWeight=weight||'700';e.style.fontSize='clamp(10px,'+(size/8.52)+'vw,'+size+'px)';e.style.lineHeight='1.12';e.style.textAlign=align||'left';e.style.whiteSpace='normal';e.style.overflow='hidden';e.style.textShadow='0 1px 4px #000,0 0 5px #000';e.style.pointerEvents='none';e.style.zIndex='24';s.append(e)}
  function r128List(s,items,x,y,w,h,size){const e=document.createElement('div');e.style.position='absolute';e.style.left=(x/8.52)+'%';e.style.top=(y/18.46)+'%';e.style.width=(w/8.52)+'%';e.style.height=(h/18.46)+'%';e.style.color='#fff';e.style.fontWeight='600';e.style.fontSize='clamp(10px,'+(size/8.52)+'vw,'+size+'px)';e.style.lineHeight='1.22';e.style.overflow='hidden';e.style.textShadow='0 1px 4px #000,0 0 5px #000';e.style.pointerEvents='none';e.style.zIndex='24';(items||[]).slice(0,4).forEach(function(t){const row=document.createElement('div');row.textContent='•  '+String(t);row.style.marginBottom='4px';e.append(row)});s.append(e)}
  function r128Long(s,text,x,y,w,h,size){const e=document.createElement('div');e.textContent=String(text||'');e.style.position='absolute';e.style.left=(x/8.52)+'%';e.style.top=(y/18.46)+'%';e.style.width=(w/8.52)+'%';e.style.height=(h/18.46)+'%';e.style.color='#fff';e.style.fontWeight='550';e.style.fontSize='clamp(11px,'+(size/8.52)+'vw,'+size+'px)';e.style.lineHeight='1.3';e.style.whiteSpace='pre-wrap';e.style.overflow='auto';e.style.paddingRight='5px';e.style.textShadow='0 1px 4px #000,0 0 5px #000';e.style.zIndex='24';e.style.touchAction='pan-y pinch-zoom';s.append(e)}
  function r128Role(c){const roles=typeof marketRolesFor==='function'?marketRolesFor(c):[];return roles[0]||c.role||c.type||'KONTRAHENT'}
  function r128Country(c){return c.countryName||countries[c.countryCode]?.name||c.countryCode||'EUROPA'}
  function r128Date(v){const d=v?new Date(v):new Date();if(Number.isNaN(d.getTime()))return String(v||'');return d.toLocaleDateString('pl-PL',{day:'2-digit',month:'2-digit',year:'numeric'})}
  function r128Clean(arr){return (arr||[]).map(function(x){return String(x||'').trim()}).filter(Boolean)}
  function r128DefaultModel(base){const c=base||{};const isDokers=/dokers/i.test(String(c.name||''));if(isDokers)return {facts:['pellet ENplus A1','ENplus ID LV 330','worki 15 kg','oferta publikowana: sierpień 2026'],offer:['380 €/t DAP Polska','pełny samochód ok. 24 t','przy pełnym TIR możliwa indywidualna niższa wycena'],conclusions:['wartościowy rekord do kalkulatora','potrzebna cena FCA Łotwa','bez FCA nie liczyć automatycznie marży eksportowej do DE'],talk:['możliwość negocjacji pełnego TIR','zapytanie o wariant FCA i DAP L&M','możliwy private-label L&M 15 kg'],source:'analiza asystenta'};
    const facts=[];if(c.availability)facts.push(c.availability);if(c.enplusId)facts.push('ENplus ID '+c.enplusId);if(c.certificate&&!facts.some(function(x){return x===c.certificate}))facts.push(c.certificate);if(c.type)facts.push(c.type);if(c.sourceDate)facts.push('dane źródłowe: '+r128Date(c.sourceDate));
    const offer=[];if(c.priceText)offer.push(c.priceText);else if(c.price)offer.push(String(c.price)+' €/t');if(c.incoterm)offer.push('Incoterm: '+c.incoterm);if(c.logistics&&c.logistics.fullTruck)offer.push(c.logistics.fullTruck);else if(c.logistics&&c.logistics.pallet)offer.push(c.logistics.pallet);if(c.payment)offer.push('Płatność: '+c.payment);
    const conclusions=[];conclusions.push('rekord do wykorzystania w kalkulatorze i rozmowie handlowej');if(c.price||c.priceText)conclusions.push('porównać warunki z kosztami L&M i docelową marżą');if((c.roles||[]).includes('DOSTAWCA')||String(c.role||'').toUpperCase().includes('DOSTAWCA'))conclusions.push('ocenić potencjał jako źródło zakupu');if((c.roles||[]).includes('KLIENT')||String(c.role||'').toUpperCase().includes('KLIENT'))conclusions.push('ocenić potencjał jako odbiorcę L&M');
    const talk=[];r128Clean(c.notes).slice(0,3).forEach(function(n){talk.push(n)});if(!talk.length&&c.availability)talk.push('odnieść rozmowę do: '+c.availability);if(!talk.length)talk.push('uzupełnić fakty przed następną rozmową');
    return {facts:r128Clean(facts),offer:r128Clean(offer),conclusions:r128Clean(conclusions),talk:r128Clean(talk),source:c.sourceLabel||'analiza asystenta'}
  }
  function r128Model(base){const c=base||getCompanyById(state.selectedCompany)||{};const d=r128DefaultModel(c),save=r128Saved(c);R128_NOTE_SECTIONS.forEach(function(k){if(Array.isArray(save[k]))d[k]=r128Clean(save[k])});d.source=save.source||d.source||'analiza asystenta';d.updatedAt=save.updatedAt||c.updatedAt||c.sourceDate||new Date().toISOString();return d}
  function r128SectionConclusion(c,key,model){const a=model[key]||[];if(key==='facts')return a[0]||'Najważniejsze fakty o firmie są zapisane w CRM.';if(key==='offer')return a[0]||'Parametry oferty wymagają uzupełnienia.';if(key==='conclusions')return a[0]||'Wnioski handlowe są gotowe do rozwijania.';return a[0]||'Fakty do rozmowy są gotowe.'}
  async function r128SyncStay(c,key){const keep=r128Id(c);try{const q=sync();if(q&&typeof q.then==='function')await q}catch(e){console.warn('R128 sync NOTATKI',e)}finally{if(keep)state.selectedCompany=keep;const cc=getCompanyById(keep)||c;setTimeout(function(){key?r128OpenNoteDetail(cc,key):r128OpenCompanyNotes(cc)},120)}}
  function r128Goal(){if(typeof r115NewTile==='function')r115NewTile('CELE ASYSTENTA');else toast('CELE ASYSTENTA — następny osobny krok MASTER')}
  function r128Dialog(c,key,mode){const m=r128Model(c);const dlg=document.createElement('dialog');dlg.style.cssText='width:min(94vw,700px);max-height:88vh;overflow:auto;border:2px solid #d7a514;border-radius:22px;background:#03150f;color:#fff;padding:18px;box-shadow:0 0 28px #d7a51488;z-index:99999';const h=document.createElement('h2');h.textContent=mode==='add'?'DODAJ NOTATKĘ':'EDYTUJ NOTATKI';h.style.cssText='margin:0 0 14px;color:#ffd229;text-align:center';dlg.append(h);const sel=document.createElement('select');sel.style.cssText='width:100%;padding:12px;border:1px solid #9b7814;border-radius:10px;background:#06110d;color:#fff;font-size:16px;margin-bottom:10px';R128_NOTE_SECTIONS.forEach(function(k){const o=document.createElement('option');o.value=k;o.textContent=R128_NOTE_LABELS[k];o.selected=k===key;sel.append(o)});dlg.append(sel);const ta=document.createElement('textarea');ta.style.cssText='width:100%;min-height:240px;box-sizing:border-box;padding:12px;border:1px solid #9b7814;border-radius:10px;background:#06110d;color:#fff;font-size:16px;line-height:1.35';function fill(){ta.value=mode==='add'?'':(m[sel.value]||[]).join('\n')}fill();sel.addEventListener('change',fill);dlg.append(ta);const bar=document.createElement('div');bar.style.cssText='display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px';const save=document.createElement('button');save.textContent='ZAPISZ';save.style.cssText='padding:13px;border:2px solid #5dff42;border-radius:12px;background:#073a11;color:#8dff76;font-weight:900';const cancel=document.createElement('button');cancel.textContent='ANULUJ';cancel.style.cssText='padding:13px;border:1px solid #777;border-radius:12px;background:#252525;color:#fff;font-weight:800';save.onclick=function(){const k=sel.value,now=r128Model(c),lines=r128Clean(String(ta.value||'').split(/\n+/));if(mode==='add')now[k]=r128Clean((now[k]||[]).concat(lines));else now[k]=lines;const patch={};R128_NOTE_SECTIONS.forEach(function(x){patch[x]=now[x]||[]});r128Write(c,patch);dlg.close();dlg.remove();if(key)r128OpenNoteDetail(c,key);else r128OpenCompanyNotes(c);toast('NOTATKI O FIRMIE — zapisano')};cancel.onclick=function(){dlg.close();dlg.remove()};bar.append(save,cancel);dlg.append(bar);document.body.append(dlg);dlg.showModal()}
  function r128MainValues(s,c,m){r128Text(s,c.name||'—',205,295,450,62,30,'#fff','900','center');r128Text(s,r128Country(c).toUpperCase(),90,405,155,50,16,'#fff','700','center');r128Text(s,r128Role(c).toUpperCase(),320,405,205,50,16,'#fff','700','center');r128Text(s,'PRIORYTET '+String(c.priority||'—').toUpperCase(),600,405,195,50,15,'#ffd43b','800','center');r128List(s,m.facts,245,500,500,172,15);r128List(s,m.offer,245,745,500,166,15);r128List(s,m.conclusions,245,990,500,166,15);r128List(s,m.talk,245,1230,500,150,15)}
  function r128OpenCompanyNotes(base){const c=base||getCompanyById(state.selectedCompany)||{};const m=r128Model(c);const s=document.createElement('section');s.className='screen r128-company-notes';s.style.position='relative';const img=document.createElement('img');img.className='master';img.src=R128_NOTES_IMG;img.alt='Notatki o firmie — MASTER';s.append(img);r128MainValues(s,c,m);s.append(hotspot({x:0,y:0,w:140,h:145,label:'Wstecz do karty firmy',onClick:render,baseW:852,baseH:1846,z:40}));s.append(hotspot({x:690,y:0,w:162,h:155,label:'Synchronizuj',onClick:function(){r128SyncStay(c,null)},baseW:852,baseH:1846,z:40}));[['facts',25,465,802,230],['offer',25,705,802,230],['conclusions',25,945,802,230],['talk',25,1185,802,225]].forEach(function(a){s.append(hotspot({x:a[1],y:a[2],w:a[3],h:a[4],label:R128_NOTE_LABELS[a[0]]+' — szczegóły',onClick:function(){r128OpenNoteDetail(c,a[0])},baseW:852,baseH:1846,z:38}))});s.append(hotspot({x:28,y:1435,w:250,h:112,label:'Edytuj',onClick:function(){r128Dialog(c,'facts','edit')},baseW:852,baseH:1846,z:40}));s.append(hotspot({x:290,y:1435,w:268,h:112,label:'Dodaj notatkę',onClick:function(){r128Dialog(c,'facts','add')},baseW:852,baseH:1846,z:40}));s.append(hotspot({x:570,y:1435,w:255,h:112,label:'Przejdź do celów',onClick:r128Goal,baseW:852,baseH:1846,z:40}));s.append(hotspot({x:28,y:1580,w:797,h:142,label:'Wróć do karty',onClick:render,baseW:852,baseH:1846,z:40}));app.replaceChildren(s);window.scrollTo(0,0)}
  function r128OpenNoteDetail(base,key){const c=base||getCompanyById(state.selectedCompany)||{},m=r128Model(c),arr=m[key]||[];const s=document.createElement('section');s.className='screen r128-note-detail';s.style.position='relative';const img=document.createElement('img');img.className='master';img.src=R128_NOTES_DETAIL_IMG;img.alt='Szczegół notatki o firmie — MASTER';s.append(img);r128Text(s,c.name||'—',205,238,450,60,29,'#fff','900','center');r128Text(s,r128Country(c).toUpperCase(),88,322,155,48,15,'#fff','700','center');r128Text(s,r128Role(c).toUpperCase(),320,322,205,48,15,'#fff','700','center');r128Text(s,'PRIORYTET '+String(c.priority||'—').toUpperCase(),600,322,195,48,14,'#ffd43b','800','center');r128Text(s,R128_NOTE_LABELS[key]||'NOTATKA',130,468,245,56,16,'#fff','800','left');r128Text(s,r128Date(m.updatedAt),535,468,220,56,16,'#fff','800','left');r128Text(s,m.source||'analiza asystenta',130,560,245,64,15,'#fff','700','left');r128Text(s,(c.name||'Firma')+' — '+(R128_NOTE_LABELS[key]||'notatka').toLowerCase(),535,560,240,64,14,'#fff','700','left');r128Long(s,arr.map(function(x){return '• '+x}).join('\n\n'),65,720,720,560,16);r128Long(s,r128SectionConclusion(c,key,m),180,1342,565,115,16);s.append(hotspot({x:0,y:0,w:140,h:145,label:'Wstecz do notatek',onClick:function(){r128OpenCompanyNotes(c)},baseW:852,baseH:1846,z:40}));s.append(hotspot({x:690,y:0,w:162,h:155,label:'Synchronizuj',onClick:function(){r128SyncStay(c,key)},baseW:852,baseH:1846,z:40}));s.append(hotspot({x:28,y:1480,w:250,h:112,label:'Edytuj wpis',onClick:function(){r128Dialog(c,key,'edit')},baseW:852,baseH:1846,z:40}));s.append(hotspot({x:290,y:1480,w:268,h:112,label:'Dodaj kolejny',onClick:function(){r128Dialog(c,key,'add')},baseW:852,baseH:1846,z:40}));s.append(hotspot({x:570,y:1480,w:255,h:112,label:'Przejdź do celów',onClick:r128Goal,baseW:852,baseH:1846,z:40}));s.append(hotspot({x:28,y:1620,w:797,h:120,label:'Wróć do notatek',onClick:function(){r128OpenCompanyNotes(c)},baseW:852,baseH:1846,z:40}));app.replaceChildren(s);window.scrollTo(0,0)}
`;
    out=out.replace('  function r115RenderCompanyMaster(){',r128Inside+'\n  function r115RenderCompanyMaster(){');
  }

  out=out.replace("onClick:()=>r115NewTile('NOTATKI O FIRMIE')","onClick:()=>r128OpenCompanyNotes(c)");
  return out;
};
